version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - cp target/smarthouse-0.0.1-SNAPSHOT.jar smarthouse-0.0.1-SNAPSHOT.jar
#      - zip smarthouse_app.zip smarthouse-0.0.1-SNAPSHOT.jar appspec.yml install.sh
artifacts:
  files:
#    - smarthouse_app.zip
    - smarthouse-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - install.sh
