version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - mkdir smarthouse_app
      - cp target/smarthouse-0.0.1-SNAPSHOT.jar smarthouse_app
      - cp appspec.yml smarthouse_app
      - cp scripts smarthouse_app
      - zip smarthouse_app.zip smarthouse_app
artifacts:
  files:
    - smarthouse_app.zip
