version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - zip target/smarthouse-0.0.1-SNAPSHOT.jar smarthouse_archive
artifacts:
  files:
    - smarthouse_archive
