cloud:
  aws:
    region:
      static: eu-west-1
    credentials:
      accessKey: AKIAWKXWUP6IXPI5O6XG
      secretKey: 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
    stack:
      auto: false
    dynamodb:
      endpoint: dynamodb.eu-west-1.amazonaws.com
      tables:
        DeviceEvents:
          name: cristi-device_events
          indexes:
            DeviceEventsHouseDeviceIndex: cristi-houseReference-deviceReference-index
        Devices:
          name: cristi-devices
    queues:
      DeviceEventsQueue: cristi-DeviceEvents
server:
  port: 8090
