cloud:
  aws:
    secrets:
      accessKeys:
        name: nocturne_smarthouse
        keys:
          accessKey: accessKey
          secretKey: secretKey
      activeMqLogin:
        name: active_mq_secret
        keys:
          activeMqUsername: login
          activeMqPassword: passcode
    region:
      static: eu-west-1
    stack:
      auto: false
    activeMq:
      endpoint: ssl://b-bfab5ea4-4f66-40e0-8ea2-415f88dd5604-1.mq.eu-west-1.amazonaws.com:61617
    dynamodb:
      endpoint: dynamodb.eu-west-1.amazonaws.com
      tables:
        DeviceEvents:
          name: nocturne-device_events
          indexes:
            DeviceEventsHouseDeviceIndex: nocturne-houseReference-deviceReference-index
        Devices:
          name: nocturne-devices
    queues:
      DeviceEventsQueue: nocturne-EventsQueue
server:
  port: 8090
