cloud:
  aws:
    secrets:
      accessKeys:
        name: nocturne_smarthouse
        keys:
          accessKey: accessKey
          secretKey: secretKey
      activeMqLogin:
        name: active_mq_secret
        keys:
          activeMqUsername: login
          activeMqPassword: passcode
    region:
      static: eu-west-1
    stack:
      auto: false
    activeMq:
      endpoint: ssl://b-00c1bbec-5b7b-49f3-bac8-61d1d0e36c28-1.mq.eu-west-1.amazonaws.com:61617
    dynamodb:
      endpoint: dynamodb.eu-west-1.amazonaws.com
      tables:
        DeviceEvents:
          name: temp_device_events
          indexes:
            DeviceEventsHouseDeviceIndex: temp_houseReference-deviceReference-index
        Devices:
          name: temp_devices
    queues:
      DeviceEventsQueue: temp-EventsQueue
server:
  port: 8090
